name: nekosama
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cloud_firestore:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  flutter_hooks:
  flutter:
    sdk: flutter
  hooks_riverpod:
  lottie:
  roggle:
  flutter_gen_runner:
  build_runner:
  flutter_screenutil:
  blobs:
  gap:
  go_router:
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
  device_preview:
  go_router_builder:

flutter:
  uses-material-design: true
  assets:
    - assets/loading/
  fonts:
   - family: Train One
     fonts:
       - asset: assets/fonts/TrainOne-Regular.ttf
   - family: NotoSansJP
     fonts:
       - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.otf


dependency_overrides:
  firebase_auth_platform_interface: 6.11.6
  firebase_core_platform_interface: 4.5.2
