name: nekosama
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.0
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  lottie: ^2.1.0
  roggle: ^0.3.0
  flutter_gen_runner: ^5.1.0+1
  build_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/loading/
  fonts:
   - family: Train One
     fonts:
       - asset: assets/fonts/TrainOne-Regular.ttf


dependency_overrides:
  firebase_auth_platform_interface: 6.11.6
  firebase_core_platform_interface: 4.5.2
