name: nekosama
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cloud_firestore:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  flutter_hooks:
  flutter:
    sdk: flutter
  hooks_riverpod:
  lottie:
  roggle:
  flutter_gen_runner:
  build_runner:
  flutter_screenutil:
  blobs:
  gap:
  go_router:
  flutter_signin_button:
  riverpod_generator:
  riverpod_annotation: ^1.1.1
  pin_code_fields: ^7.4.0
  timelines: ^0.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  uuid: ^3.0.7
  salomon_bottom_bar: ^3.3.1
  chewie: ^1.3.6
  video_player: ^2.4.10
  image_picker: ^0.8.6
  firebase_storage: ^11.0.10
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
  device_preview:
  go_router_builder:
  freezed: ^2.3.2
  json_serializable: ^6.5.4


flutter:
  uses-material-design: true
  assets:
    - assets/loading/
    - assets/images/
    - assets/tabs/
    - assets/post/

  fonts:
   - family: Train One
     fonts:
       - asset: assets/fonts/TrainOne-Regular.ttf
   - family: NotoSansJP
     fonts:
       - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.otf


dependency_overrides:
  firebase_auth_platform_interface: 6.11.6
  firebase_core_platform_interface: 4.5.2
